1. Wiki/encyclopedia/urls.py
from django.urls import path
from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.show, name="show"),
    path("search", views.search, name="search"),
    path("add", views.add, name="add"),
    path("wiki/<str:title>/edit", views.edit, name="edit"),
    path("random", views.random, name="random")
]

1. Wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

1. Wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

1. Wiki/encyclopedia/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from . import util
from django import forms
from django.urls import reverse
from random import shuffle
import markdown2

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(), 
        'message': "All pages" 
    })

def show(request, title):
    entries = util.list_entries()
    content = util.get_entry(title) 
    if content != None :
        return render(request, "encyclopedia/show.html", {
        "title": title, 
        "content": markdown2.markdown(str(content))
        })
    else :
        return HttpResponse(f"Error : the requested page was not Found.")

def search(request):
    user_query = request.POST.get('user_query')
    entry = util.get_entry(user_query)
    titles_list = util.list_titles()
    if user_query in titles_list: 
        return render(request, "encyclopedia/show.html", {
            "title": user_query,
            "content": entry
        })
    else :  
        similar_titles = []
        for title in titles_list :
            if user_query in title :
                similar_titles.append(title)

        return render(request, "encyclopedia/index.html", {
            "message": "You're probably looking for...",
            "entries": similar_titles
        })

class AddEntryForm(forms.Form):
    title = forms.CharField(label="Title")
    content = forms.CharField(label="Content", widget=forms.Textarea())

def add(request):
    titles_list = util.list_titles()
    if request.method == "POST" :
        form = AddEntryForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            
            if title in titles_list :
                return HttpResponse(f"Error : this entry already exists")
            else: 
                util.save_entry(title, content)
                return render(request, "encyclopedia/show.html", {
                    "title": title,
                    "content": content
                })
        else:
            return render(request, "encyclopedia/add.html", { 
                "form": form 
            })

    if request.method == "GET" :
        return render(request, "encyclopedia/add.html", { 
            "form": AddEntryForm() 
        })

def edit(request, title):
    old_title = title
    old_content = util.get_entry(title)
    if request.method == "POST" :
        if request.POST.get('title') :
            new_title = request.POST.get('title')
        else :
            new_title = old_title
        if request.POST.get('content') :
            new_content = request.POST.get('content')
        else :
            new_content = old_content
        util.save_entry(new_title, new_content)
        return render(request, "encyclopedia/show.html", {
            "title": new_title,
            "content": new_content
        })
    if request.method == "GET" :
        return render(request, "encyclopedia/edit.html", { 
            "title": old_title, 
            "content": old_content
        })

def random(request):
    titles = util.list_titles()
    #random_title = random.choice(titles)
    shuffle(titles)
    random_title = titles[3]
    random_content = util.get_entry(random_title)
    return render(request, "encyclopedia/show.html", {
        "title": random_title,
        "content": random_content, 
    })

1. Wiki/encyclopedia/templates/encyclopedia/add.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Add a new entry:</h1>

    <form action="{% url 'encyclopedia:add' %}" method="POST">
    	{% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>

{% endblock %}

1. Wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Modify this entry:</h1>

    <form action="{% url 'encyclopedia:edit' title=title %}" method="POST">
    	{% csrf_token %}
    	<label for="title">Title : </label><br>
        <input type="text" name="title" placeholder="{{ title }}">
        <br>
        <br>
        <label for="content">Content : </label><br>
   		<textarea id="content_field" name="content" placeholder="{{content }}"></textarea><br><br>
        <input type="submit" value="Modify">
    </form>

{% endblock %}

1. Wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>{{message}}</h1>

    <ul>
        
        {% for entry in entries %}
            <li><a href="/wiki/{{entry}}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

1. Wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="user_query" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:add'%}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random'%} ">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

1. Wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Search Results</h1>

    <ul>
        {% for entry in similar_entries %}
            <li><a href="/wiki/{{entry}}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

1. Wiki/encyclopedia/templates/encyclopedia/show.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}
	<p>{{title}}</p>
    <p>{{content}}</p>
	<div>
	    <a href="{% url 'encyclopedia:edit' title=title %}">Edit</a>
	</div>
{% endblock %}